/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoClientRouteImport } from './routes/demo/client'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedClientRouteImport } from './routes/_authenticated/client'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DemoClientIndexRouteImport } from './routes/demo/client/index'
import { Route as AuthenticatedSupervisorIndexRouteImport } from './routes/_authenticated/supervisor/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as DemoClientSpecialsRouteImport } from './routes/demo/client/specials'
import { Route as DemoClientHistoryRouteImport } from './routes/demo/client/history'
import { Route as DemoClientCommentsRouteImport } from './routes/demo/client/comments'
import { Route as AuthenticatedSupervisorIssuesRouteImport } from './routes/_authenticated/supervisor/issues'
import { Route as AuthenticatedSupervisorHistoryRouteImport } from './routes/_authenticated/supervisor/history'
import { Route as AuthenticatedClientSpecialProjectsRouteImport } from './routes/_authenticated/client/special-projects'
import { Route as AuthenticatedClientIssuesRouteImport } from './routes/_authenticated/client/issues'
import { Route as AuthenticatedClientHistoryRouteImport } from './routes/_authenticated/client/history'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPropertiesRouteImport } from './routes/_authenticated/admin/properties'
import { Route as AuthenticatedAdminIssuesRouteImport } from './routes/_authenticated/admin/issues'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedSupervisorPropertyIdRouteImport } from './routes/_authenticated/supervisor/property.$id'
import { Route as AuthenticatedClientPropertyIdRouteImport } from './routes/_authenticated/client/property.$id'
import { Route as AuthenticatedAdminPropertiesIdRouteImport } from './routes/_authenticated/admin/properties.$id'
import { Route as AuthenticatedAdminPropertyIdViewRouteImport } from './routes/_authenticated/admin/property.$id.view'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoClientRoute = DemoClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => DemoRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientRoute = AuthenticatedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoClientIndexRoute = DemoClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoClientRoute,
} as any)
const AuthenticatedSupervisorIndexRoute =
  AuthenticatedSupervisorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const DemoClientSpecialsRoute = DemoClientSpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => DemoClientRoute,
} as any)
const DemoClientHistoryRoute = DemoClientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DemoClientRoute,
} as any)
const DemoClientCommentsRoute = DemoClientCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => DemoClientRoute,
} as any)
const AuthenticatedSupervisorIssuesRoute =
  AuthenticatedSupervisorIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedSupervisorHistoryRoute =
  AuthenticatedSupervisorHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedClientSpecialProjectsRoute =
  AuthenticatedClientSpecialProjectsRouteImport.update({
    id: '/special-projects',
    path: '/special-projects',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientIssuesRoute =
  AuthenticatedClientIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedClientHistoryRoute =
  AuthenticatedClientHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPropertiesRoute =
  AuthenticatedAdminPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIssuesRoute =
  AuthenticatedAdminIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSupervisorPropertyIdRoute =
  AuthenticatedSupervisorPropertyIdRouteImport.update({
    id: '/property/$id',
    path: '/property/$id',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedClientPropertyIdRoute =
  AuthenticatedClientPropertyIdRouteImport.update({
    id: '/property/$id',
    path: '/property/$id',
    getParentRoute: () => AuthenticatedClientRoute,
  } as any)
const AuthenticatedAdminPropertiesIdRoute =
  AuthenticatedAdminPropertiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPropertiesRoute,
  } as any)
const AuthenticatedAdminPropertyIdViewRoute =
  AuthenticatedAdminPropertyIdViewRouteImport.update({
    id: '/property/$id/view',
    path: '/property/$id/view',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/client': typeof AuthenticatedClientRouteWithChildren
  '/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/demo/client': typeof DemoClientRouteWithChildren
  '/demo/': typeof DemoIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/history': typeof AuthenticatedClientHistoryRoute
  '/client/issues': typeof AuthenticatedClientIssuesRoute
  '/client/special-projects': typeof AuthenticatedClientSpecialProjectsRoute
  '/supervisor/history': typeof AuthenticatedSupervisorHistoryRoute
  '/supervisor/issues': typeof AuthenticatedSupervisorIssuesRoute
  '/demo/client/comments': typeof DemoClientCommentsRoute
  '/demo/client/history': typeof DemoClientHistoryRoute
  '/demo/client/specials': typeof DemoClientSpecialsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
  '/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/demo/client/': typeof DemoClientIndexRoute
  '/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/client/property/$id': typeof AuthenticatedClientPropertyIdRoute
  '/supervisor/property/$id': typeof AuthenticatedSupervisorPropertyIdRoute
  '/admin/property/$id/view': typeof AuthenticatedAdminPropertyIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/demo': typeof DemoIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/admin/properties': typeof AuthenticatedAdminPropertiesRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/client/history': typeof AuthenticatedClientHistoryRoute
  '/client/issues': typeof AuthenticatedClientIssuesRoute
  '/client/special-projects': typeof AuthenticatedClientSpecialProjectsRoute
  '/supervisor/history': typeof AuthenticatedSupervisorHistoryRoute
  '/supervisor/issues': typeof AuthenticatedSupervisorIssuesRoute
  '/demo/client/comments': typeof DemoClientCommentsRoute
  '/demo/client/history': typeof DemoClientHistoryRoute
  '/demo/client/specials': typeof DemoClientSpecialsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
  '/supervisor': typeof AuthenticatedSupervisorIndexRoute
  '/demo/client': typeof DemoClientIndexRoute
  '/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/client/property/$id': typeof AuthenticatedClientPropertyIdRoute
  '/supervisor/property/$id': typeof AuthenticatedSupervisorPropertyIdRoute
  '/admin/property/$id/view': typeof AuthenticatedAdminPropertyIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/client': typeof AuthenticatedClientRouteWithChildren
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/demo/client': typeof DemoClientRouteWithChildren
  '/demo/': typeof DemoIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/_authenticated/admin/properties': typeof AuthenticatedAdminPropertiesRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/client/history': typeof AuthenticatedClientHistoryRoute
  '/_authenticated/client/issues': typeof AuthenticatedClientIssuesRoute
  '/_authenticated/client/special-projects': typeof AuthenticatedClientSpecialProjectsRoute
  '/_authenticated/supervisor/history': typeof AuthenticatedSupervisorHistoryRoute
  '/_authenticated/supervisor/issues': typeof AuthenticatedSupervisorIssuesRoute
  '/demo/client/comments': typeof DemoClientCommentsRoute
  '/demo/client/history': typeof DemoClientHistoryRoute
  '/demo/client/specials': typeof DemoClientSpecialsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
  '/_authenticated/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/demo/client/': typeof DemoClientIndexRoute
  '/_authenticated/admin/properties/$id': typeof AuthenticatedAdminPropertiesIdRoute
  '/_authenticated/client/property/$id': typeof AuthenticatedClientPropertyIdRoute
  '/_authenticated/supervisor/property/$id': typeof AuthenticatedSupervisorPropertyIdRoute
  '/_authenticated/admin/property/$id/view': typeof AuthenticatedAdminPropertyIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/demo'
    | '/login'
    | '/pending'
    | '/privacy'
    | '/support'
    | '/admin'
    | '/client'
    | '/supervisor'
    | '/demo/client'
    | '/demo/'
    | '/admin/analytics'
    | '/admin/issues'
    | '/admin/properties'
    | '/admin/users'
    | '/client/history'
    | '/client/issues'
    | '/client/special-projects'
    | '/supervisor/history'
    | '/supervisor/issues'
    | '/demo/client/comments'
    | '/demo/client/history'
    | '/demo/client/specials'
    | '/admin/'
    | '/client/'
    | '/supervisor/'
    | '/demo/client/'
    | '/admin/properties/$id'
    | '/client/property/$id'
    | '/supervisor/property/$id'
    | '/admin/property/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/pending'
    | '/privacy'
    | '/support'
    | '/demo'
    | '/admin/analytics'
    | '/admin/issues'
    | '/admin/properties'
    | '/admin/users'
    | '/client/history'
    | '/client/issues'
    | '/client/special-projects'
    | '/supervisor/history'
    | '/supervisor/issues'
    | '/demo/client/comments'
    | '/demo/client/history'
    | '/demo/client/specials'
    | '/admin'
    | '/client'
    | '/supervisor'
    | '/demo/client'
    | '/admin/properties/$id'
    | '/client/property/$id'
    | '/supervisor/property/$id'
    | '/admin/property/$id/view'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/demo'
    | '/login'
    | '/pending'
    | '/privacy'
    | '/support'
    | '/_authenticated/admin'
    | '/_authenticated/client'
    | '/_authenticated/supervisor'
    | '/demo/client'
    | '/demo/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/issues'
    | '/_authenticated/admin/properties'
    | '/_authenticated/admin/users'
    | '/_authenticated/client/history'
    | '/_authenticated/client/issues'
    | '/_authenticated/client/special-projects'
    | '/_authenticated/supervisor/history'
    | '/_authenticated/supervisor/issues'
    | '/demo/client/comments'
    | '/demo/client/history'
    | '/demo/client/specials'
    | '/_authenticated/admin/'
    | '/_authenticated/client/'
    | '/_authenticated/supervisor/'
    | '/demo/client/'
    | '/_authenticated/admin/properties/$id'
    | '/_authenticated/client/property/$id'
    | '/_authenticated/supervisor/property/$id'
    | '/_authenticated/admin/property/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/client': {
      id: '/demo/client'
      path: '/client'
      fullPath: '/demo/client'
      preLoaderRoute: typeof DemoClientRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client': {
      id: '/_authenticated/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof AuthenticatedClientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo/client/': {
      id: '/demo/client/'
      path: '/'
      fullPath: '/demo/client/'
      preLoaderRoute: typeof DemoClientIndexRouteImport
      parentRoute: typeof DemoClientRoute
    }
    '/_authenticated/supervisor/': {
      id: '/_authenticated/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof AuthenticatedSupervisorIndexRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/demo/client/specials': {
      id: '/demo/client/specials'
      path: '/specials'
      fullPath: '/demo/client/specials'
      preLoaderRoute: typeof DemoClientSpecialsRouteImport
      parentRoute: typeof DemoClientRoute
    }
    '/demo/client/history': {
      id: '/demo/client/history'
      path: '/history'
      fullPath: '/demo/client/history'
      preLoaderRoute: typeof DemoClientHistoryRouteImport
      parentRoute: typeof DemoClientRoute
    }
    '/demo/client/comments': {
      id: '/demo/client/comments'
      path: '/comments'
      fullPath: '/demo/client/comments'
      preLoaderRoute: typeof DemoClientCommentsRouteImport
      parentRoute: typeof DemoClientRoute
    }
    '/_authenticated/supervisor/issues': {
      id: '/_authenticated/supervisor/issues'
      path: '/issues'
      fullPath: '/supervisor/issues'
      preLoaderRoute: typeof AuthenticatedSupervisorIssuesRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/supervisor/history': {
      id: '/_authenticated/supervisor/history'
      path: '/history'
      fullPath: '/supervisor/history'
      preLoaderRoute: typeof AuthenticatedSupervisorHistoryRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/client/special-projects': {
      id: '/_authenticated/client/special-projects'
      path: '/special-projects'
      fullPath: '/client/special-projects'
      preLoaderRoute: typeof AuthenticatedClientSpecialProjectsRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/issues': {
      id: '/_authenticated/client/issues'
      path: '/issues'
      fullPath: '/client/issues'
      preLoaderRoute: typeof AuthenticatedClientIssuesRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/client/history': {
      id: '/_authenticated/client/history'
      path: '/history'
      fullPath: '/client/history'
      preLoaderRoute: typeof AuthenticatedClientHistoryRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/properties': {
      id: '/_authenticated/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/issues': {
      id: '/_authenticated/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AuthenticatedAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/supervisor/property/$id': {
      id: '/_authenticated/supervisor/property/$id'
      path: '/property/$id'
      fullPath: '/supervisor/property/$id'
      preLoaderRoute: typeof AuthenticatedSupervisorPropertyIdRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/client/property/$id': {
      id: '/_authenticated/client/property/$id'
      path: '/property/$id'
      fullPath: '/client/property/$id'
      preLoaderRoute: typeof AuthenticatedClientPropertyIdRouteImport
      parentRoute: typeof AuthenticatedClientRoute
    }
    '/_authenticated/admin/properties/$id': {
      id: '/_authenticated/admin/properties/$id'
      path: '/$id'
      fullPath: '/admin/properties/$id'
      preLoaderRoute: typeof AuthenticatedAdminPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPropertiesRoute
    }
    '/_authenticated/admin/property/$id/view': {
      id: '/_authenticated/admin/property/$id/view'
      path: '/property/$id/view'
      fullPath: '/admin/property/$id/view'
      preLoaderRoute: typeof AuthenticatedAdminPropertyIdViewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminPropertiesRouteChildren {
  AuthenticatedAdminPropertiesIdRoute: typeof AuthenticatedAdminPropertiesIdRoute
}

const AuthenticatedAdminPropertiesRouteChildren: AuthenticatedAdminPropertiesRouteChildren =
  {
    AuthenticatedAdminPropertiesIdRoute: AuthenticatedAdminPropertiesIdRoute,
  }

const AuthenticatedAdminPropertiesRouteWithChildren =
  AuthenticatedAdminPropertiesRoute._addFileChildren(
    AuthenticatedAdminPropertiesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminIssuesRoute: typeof AuthenticatedAdminIssuesRoute
  AuthenticatedAdminPropertiesRoute: typeof AuthenticatedAdminPropertiesRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPropertyIdViewRoute: typeof AuthenticatedAdminPropertyIdViewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminIssuesRoute: AuthenticatedAdminIssuesRoute,
  AuthenticatedAdminPropertiesRoute:
    AuthenticatedAdminPropertiesRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPropertyIdViewRoute: AuthenticatedAdminPropertyIdViewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedClientRouteChildren {
  AuthenticatedClientHistoryRoute: typeof AuthenticatedClientHistoryRoute
  AuthenticatedClientIssuesRoute: typeof AuthenticatedClientIssuesRoute
  AuthenticatedClientSpecialProjectsRoute: typeof AuthenticatedClientSpecialProjectsRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
  AuthenticatedClientPropertyIdRoute: typeof AuthenticatedClientPropertyIdRoute
}

const AuthenticatedClientRouteChildren: AuthenticatedClientRouteChildren = {
  AuthenticatedClientHistoryRoute: AuthenticatedClientHistoryRoute,
  AuthenticatedClientIssuesRoute: AuthenticatedClientIssuesRoute,
  AuthenticatedClientSpecialProjectsRoute:
    AuthenticatedClientSpecialProjectsRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
  AuthenticatedClientPropertyIdRoute: AuthenticatedClientPropertyIdRoute,
}

const AuthenticatedClientRouteWithChildren =
  AuthenticatedClientRoute._addFileChildren(AuthenticatedClientRouteChildren)

interface AuthenticatedSupervisorRouteChildren {
  AuthenticatedSupervisorHistoryRoute: typeof AuthenticatedSupervisorHistoryRoute
  AuthenticatedSupervisorIssuesRoute: typeof AuthenticatedSupervisorIssuesRoute
  AuthenticatedSupervisorIndexRoute: typeof AuthenticatedSupervisorIndexRoute
  AuthenticatedSupervisorPropertyIdRoute: typeof AuthenticatedSupervisorPropertyIdRoute
}

const AuthenticatedSupervisorRouteChildren: AuthenticatedSupervisorRouteChildren =
  {
    AuthenticatedSupervisorHistoryRoute: AuthenticatedSupervisorHistoryRoute,
    AuthenticatedSupervisorIssuesRoute: AuthenticatedSupervisorIssuesRoute,
    AuthenticatedSupervisorIndexRoute: AuthenticatedSupervisorIndexRoute,
    AuthenticatedSupervisorPropertyIdRoute:
      AuthenticatedSupervisorPropertyIdRoute,
  }

const AuthenticatedSupervisorRouteWithChildren =
  AuthenticatedSupervisorRoute._addFileChildren(
    AuthenticatedSupervisorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClientRoute: typeof AuthenticatedClientRouteWithChildren
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClientRoute: AuthenticatedClientRouteWithChildren,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DemoClientRouteChildren {
  DemoClientCommentsRoute: typeof DemoClientCommentsRoute
  DemoClientHistoryRoute: typeof DemoClientHistoryRoute
  DemoClientSpecialsRoute: typeof DemoClientSpecialsRoute
  DemoClientIndexRoute: typeof DemoClientIndexRoute
}

const DemoClientRouteChildren: DemoClientRouteChildren = {
  DemoClientCommentsRoute: DemoClientCommentsRoute,
  DemoClientHistoryRoute: DemoClientHistoryRoute,
  DemoClientSpecialsRoute: DemoClientSpecialsRoute,
  DemoClientIndexRoute: DemoClientIndexRoute,
}

const DemoClientRouteWithChildren = DemoClientRoute._addFileChildren(
  DemoClientRouteChildren,
)

interface DemoRouteChildren {
  DemoClientRoute: typeof DemoClientRouteWithChildren
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoClientRoute: DemoClientRouteWithChildren,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
